name: Run Databricks ETL

on:
  workflow_dispatch:
    inputs:
      process_date:
        description: 'Process date for ETL'
        required: true
        default: '2025-08-15'

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Databricks Job via REST API
        run: |
          echo "Triggering Databricks ETL job for date ${{ github.event.inputs.process_date }}"
          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.1/jobs/run-now" \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "job_id": "'"${{ secrets.DATABRICKS_JOB_ID }}"'",
                  "notebook_params": {
                    "process_date": "'"${{ github.event.inputs.process_date }}"'"
                  }
                }'
